on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: hydephp/action@master
        with:
          deploy-to: "pages"
          env: |
            SITE_NAME="An open source enthusiast and his stories."
            SITE_URL=https://www.dannyvandersluijs.nl
            TORCHLIGHT_TOKEN=${{ secrets.TORCHLIGHT_TOKEN }}